### ISSUE TITLE
How to get position for more than one rigid bodies

### ISSUE THREAD

**Issue by binxxx** [crigroup/optitrack#4]
Hi, thanks for this package to read data from OptiTrack. It works fine to get data for one rigid body. While I want it to read data from two rigid bodies, how can I achieve that? Do I need to modify the config file? Can you give me some examples about that?

```
parent_frame: world
optitrack_frame: optitrack
# Rate in Hz
tf_publish_rate: 50.

# Mapping between rigid body ID and name to be use in TF
rigid_bodies:
  bstick:
    id: 2
    markers:
      - [22.378,  -0.158,   -10.189]
      - [-25.409, 114.359,  2.920]
      - [13.729,  114.186,  2.757]
      - [-24.982, -114.268, 2.381]
      - [14.284,  -114.119, 2.131]
```

**Comment by fsuarez6** [comment]
You need to pass the rigid bodies details to the node. One way to do that, would be by modifying the config file as you mention. A better way would be to create your own launch file + config file and customize them as required.
Here an example of a config file for several markers:
```yaml
parent_frame: world
optitrack_frame: optitrack
# Rate in Hz
tf_publish_rate: 50.

# Mapping between rigid body ID and name to be use in TF
rigid_bodies:
  marker_01_name:
    id: 1
  marker_02_name:
    id: 2
  custom_name:
    id: 3
```
For your reference: 
- The rigid bodies mapping is loaded between [lines 30 to 35](https://github.com/crigroup/optitrack/blob/0e14a7cb896d04b73af34b0e0eed5d4ed16f7f0f/scripts/rigid_bodies_publisher.py#L33) of the `rigid_bodies_publisher.py` node.
- In [line 98](https://github.com/crigroup/optitrack/blob/0e14a7cb896d04b73af34b0e0eed5d4ed16f7f0f/scripts/rigid_bodies_publisher.py#L98) is where the mapping is used.
- You can easy check all the available rigid bodies using: `rostopic echo /optitrack/rigid_bodies`

Please, let me know if it works to include these details in the README.
